version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: smintank/kittygram_backend
    env_file: .env
    volumes:
      - static:/app/backend_static/
      - media:/app/media/
    depends_on:
      - db
        
  frontend:
    image: smintank/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/

  gateway:
    image: smintank/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static/
      - media:/media/
